// ---------------------------------------------------Imports------------------------------------------------
import Footer from "./_components/footer/Footer";
import Header from "./_components/header/Header";
// ----------------------------------------------------------------------------------------------------------

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
